"""
AI research report generation (Claude API).

IMPORTANT DESIGN PRINCIPLE — separation of fact and interpretation:
  - Everything fed INTO the model is objective data collected upstream.
  - The model's output is clearly labeled as AI-GENERATED INTERPRETATION.
  - Analyst consensus (if present) is REAL analyst opinion, passed through.

The report never invents numbers: the prompt instructs the model to only
reference figures present in the input data.
"""

import json
import anthropic

import config

SYSTEM_PROMPT = """You are an equity research analyst writing an institutional-style research note.

STRICT RULES:
- Use ONLY the numbers provided in the data. Never invent or estimate figures.
- Clearly separate FACTS (the data given) from INTERPRETATION (your analysis).
- When analyst consensus data is provided, attribute it explicitly to analysts, not to yourself.
- If a data point is missing, say so rather than guessing.
- Be balanced: every thesis must include both a bull case and a bear case.
- No hedging filler. Direct, professional language.
"""

REPORT_TEMPLATE = """Generate a one-page equity research note with these sections:

## Company Snapshot
2-3 sentences: what the company does, sector, market cap context.

## Valuation
Where the stock trades vs peers (use the relative valuation data).
State explicitly whether the multiples imply premium or discount and on which metrics.

## Fundamentals Assessment
Margins, returns on capital, growth, balance sheet — what the numbers say.

## Analyst Consensus (if available)
Real analyst price targets and recent rating actions. Attribute clearly.

## Macro Context (if available)
How the current rate/inflation environment matters for this name.

## Bull Case / Bear Case
3 points each, grounded in the data provided.

## Bottom Line
2-3 sentences. What an investor should focus on. Do NOT give a buy/sell recommendation —
state what the data supports and what the key uncertainties are.

DATA:
{data_json}
"""


def generate_report(payload: dict) -> str:
    """
    payload: dict with keys like fundamentals, price_stats, relative_valuation,
    analyst_data, insider_activity, macro_context.
    Returns markdown report text.
    """
    if not config.ANTHROPIC_API_KEY:
        return _fallback_report(payload)

    client = anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY)
    prompt = REPORT_TEMPLATE.format(data_json=json.dumps(payload, indent=2, default=str))

    last_error = None
    for model in config.CLAUDE_MODELS:
        try:
            msg = client.messages.create(
                model=model,
                max_tokens=2000,
                system=SYSTEM_PROMPT,
                messages=[{"role": "user", "content": prompt}],
            )
            text = "".join(b.text for b in msg.content if hasattr(b, "text"))
            header = (
                f"# AI-Generated Research Note — {payload.get('ticker', '')}\n\n"
                f"*Interpretation generated by {model} from objective data. "
                f"Analyst consensus figures, where shown, are real analyst opinions.*\n\n"
            )
            return header + text
        except Exception as e:
            last_error = e
            continue

    return _fallback_report(payload) + f"\n\n(AI generation failed: {last_error})"


def _fallback_report(payload: dict) -> str:
    """Plain data dump when no API key — still useful, just not interpreted."""
    return (
        f"# Data Summary — {payload.get('ticker', '')}\n\n"
        "ANTHROPIC_API_KEY not set — showing raw data without AI interpretation.\n\n"
        "```json\n" + json.dumps(payload, indent=2, default=str) + "\n```"
    )


TRANSCRIPT_SYSTEM = """You are an equity research analyst reviewing an earnings call transcript.
Extract structured insights from the transcript only. Do not invent information not present in the text.
Return valid JSON matching the requested schema exactly."""

TRANSCRIPT_PROMPT = """Analyze this earnings call transcript for {ticker}.

Extract:
1. management_guidance — next quarter guidance or outlook (revenue, EPS, margins, or qualitative; null if not stated)
2. key_risks — list of key risks management mentioned
3. sentiment — overall tone: "bullish", "neutral", or "bearish"
4. top_quotes — exactly 3 most important executive quotes, each with "speaker" and "quote"

Return ONLY a JSON object with those keys.

TRANSCRIPT:
{transcript}
"""

PORTFOLIO_BRIEF_SYSTEM = """You are a portfolio strategist writing a concise weekly brief for an investor.
Use only the data provided. Be direct and actionable. No buy/sell recommendations."""

PORTFOLIO_BRIEF_PROMPT = """Write a weekly portfolio brief covering all holdings below.

Include:
- Portfolio overview (composition, notable movers)
- Key themes across holdings
- Risks to watch this week
- 3 bullet points of what matters most

Holdings data:
{data_json}
"""


def _call_claude(system: str, prompt: str, max_tokens: int = 2000) -> str | None:
    if not config.ANTHROPIC_API_KEY:
        return None
    client = anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY)
    for model in config.CLAUDE_MODELS:
        try:
            msg = client.messages.create(
                model=model,
                max_tokens=max_tokens,
                system=system,
                messages=[{"role": "user", "content": prompt}],
            )
            return "".join(b.text for b in msg.content if hasattr(b, "text"))
        except Exception:
            continue
    return None


def _parse_json_response(text: str) -> dict:
    text = text.strip()
    if text.startswith("```"):
        text = text.split("```", 2)[1]
        if text.startswith("json"):
            text = text[4:]
    return json.loads(text.strip())


def analyze_transcript(transcript_text: str, ticker: str) -> dict:
    """
    Extract guidance, risks, sentiment, and top quotes from an earnings transcript.
    Returns structured dict; falls back gracefully without API key.
    """
    if not transcript_text or len(transcript_text.strip()) < 200:
        return {"available": False, "note": "Transcript too short to analyze"}

    truncated = transcript_text[:120_000]
    if not config.ANTHROPIC_API_KEY:
        return {
            "available": False,
            "note": "ANTHROPIC_API_KEY not set — transcript collected but not analyzed",
            "char_count": len(transcript_text),
        }

    prompt = TRANSCRIPT_PROMPT.format(ticker=ticker.upper(), transcript=truncated)
    raw = _call_claude(TRANSCRIPT_SYSTEM, prompt, max_tokens=1500)
    if not raw:
        return {"available": False, "note": "Claude API call failed"}

    try:
        parsed = _parse_json_response(raw)
        return {
            "available": True,
            "ticker": ticker.upper(),
            "management_guidance": parsed.get("management_guidance"),
            "key_risks": parsed.get("key_risks", []),
            "sentiment": parsed.get("sentiment", "neutral"),
            "top_quotes": parsed.get("top_quotes", []),
        }
    except (json.JSONDecodeError, KeyError) as e:
        return {"available": False, "note": f"Failed to parse transcript analysis: {e}"}


def generate_portfolio_brief(portfolio_data: list[dict]) -> str:
    """AI weekly brief for all portfolio holdings."""
    if not portfolio_data:
        return "No portfolio holdings to brief."

    if not config.ANTHROPIC_API_KEY:
        return (
            "ANTHROPIC_API_KEY not set — cannot generate portfolio brief.\n\n"
            + json.dumps(portfolio_data, indent=2, default=str)
        )

    prompt = PORTFOLIO_BRIEF_PROMPT.format(
        data_json=json.dumps(portfolio_data, indent=2, default=str)
    )
    text = _call_claude(PORTFOLIO_BRIEF_SYSTEM, prompt, max_tokens=1500)
    if not text:
        return "AI brief generation failed."
    return f"# Weekly Portfolio Brief\n\n*AI-generated from current holdings and prices.*\n\n{text}"
