"""
Fundamentals & price data collection.

Primary source: Alpha Vantage OVERVIEW (if ALPHA_VANTAGE_API_KEY is set) — P/E and
revenue growth without yfinance rate limits.
Fallback: yfinance — free but occasionally incomplete.

Everything returned here is OBJECTIVE data (reported financials, market prices).
No opinions, no estimates generated by us.
"""

import requests
import pandas as pd
from datetime import date

import config
import market_cache
from yfinance_client import yf_analyst_price_targets, yf_download, yf_ticker_info

FMP_BASE = "https://financialmodelingprep.com/api/v3"
ALPHAVANTAGE_BASE = "https://www.alphavantage.co/query"


# ---------------------------------------------------------------------------
# Price data (always yfinance — free and good enough for prices)
# ---------------------------------------------------------------------------

def get_price_history(ticker: str, years: int = config.PRICE_LOOKBACK_YEARS) -> pd.DataFrame:
    """Daily OHLCV history for the ticker. Returns empty DataFrame on failure."""
    ticker = ticker.upper()
    cached = market_cache.get_price_history(ticker, years)
    if cached is not None and not cached.empty:
        return cached

    try:
        data = yf_download(ticker, period=f"{years}y", auto_adjust=True, progress=False)
        if data.empty:
            print(f"[error] yfinance returned empty price data for {ticker}")
            return pd.DataFrame()
        if isinstance(data.columns, pd.MultiIndex):
            data.columns = data.columns.get_level_values(0)
        market_cache.set_price_history(ticker, years, data)
        return data
    except Exception as e:
        print(f"[error] yfinance price history failed for {ticker}: {e}")
        return pd.DataFrame()


def get_price_stats(prices: pd.DataFrame, ticker: str = "") -> dict:
    """Objective price-derived statistics. Returns available=False if data missing."""
    label = ticker or "ticker"
    try:
        if prices is None or prices.empty or "Close" not in prices.columns:
            note = f"No price data available for {label}"
            print(f"[error] {note}")
            return {"available": False, "note": note}

        close = prices["Close"].dropna()
        if close.empty:
            note = f"No valid closing prices for {label}"
            print(f"[error] {note}")
            return {"available": False, "note": note}

        daily_ret = close.pct_change().dropna()
        ann_return = daily_ret.mean() * 252
        ann_vol = daily_ret.std() * (252 ** 0.5)
        sharpe = (ann_return - config.RISK_FREE_RATE) / ann_vol if ann_vol > 0 else None
        cummax = close.cummax()
        drawdown = (close / cummax - 1).min()

        return {
            "available": True,
            "last_price": round(float(close.iloc[-1]), 2),
            "return_1y": round(float(close.iloc[-1] / close.iloc[-min(252, len(close))] - 1), 4),
            "annualized_return": round(float(ann_return), 4),
            "annualized_volatility": round(float(ann_vol), 4),
            "sharpe_ratio": round(float(sharpe), 2) if sharpe is not None else None,
            "max_drawdown": round(float(drawdown), 4),
            "high_52w": round(float(close.iloc[-252:].max()), 2) if len(close) >= 252 else None,
            "low_52w": round(float(close.iloc[-252:].min()), 2) if len(close) >= 252 else None,
        }
    except Exception as e:
        note = f"Price stats calculation failed for {label}: {e}"
        print(f"[error] {note}")
        return {"available": False, "note": note}


# ---------------------------------------------------------------------------
# Fundamentals — Alpha Vantage primary, yfinance fallback
# ---------------------------------------------------------------------------

def _alphavantage_overview(ticker: str) -> dict:
    r = requests.get(
        ALPHAVANTAGE_BASE,
        params={
            "function": "OVERVIEW",
            "symbol": ticker,
            "apikey": config.ALPHA_VANTAGE_API_KEY,
        },
        timeout=20,
    )
    r.raise_for_status()
    data = r.json()
    if not isinstance(data, dict):
        raise ValueError(f"Alpha Vantage returned invalid overview for {ticker}")
    if data.get("Symbol") is None:
        msg = data.get("Note") or data.get("Information") or data.get("Error Message")
        raise ValueError(msg or f"Alpha Vantage returned no overview for {ticker}")
    return data


def _av_float(val) -> float | None:
    if val is None:
        return None
    if isinstance(val, (int, float)):
        return float(val)
    s = str(val).strip()
    if not s or s.lower() in ("none", "null", "-", "n/a"):
        return None
    try:
        return float(s)
    except ValueError:
        return None


def _overview_metric(overview: dict, *keys: str) -> float | None:
    for key in keys:
        val = _av_float(overview.get(key))
        if val is not None:
            return val
    return None


def _fundamentals_alphavantage(ticker: str) -> dict:
    overview = _alphavantage_overview(ticker)
    return {
        "available": True,
        "source": "Alpha Vantage",
        "company_name": overview.get("Name"),
        "sector": overview.get("Sector"),
        "industry": overview.get("Industry"),
        "market_cap": _overview_metric(overview, "MarketCapitalization"),
        "pe_ttm": _overview_metric(overview, "PERatio"),
        "forward_pe": _overview_metric(overview, "ForwardPE"),
        "peg_ratio": _overview_metric(overview, "PEGRatio"),
        "ev_ebitda": _overview_metric(overview, "EVToEBITDA"),
        "ev_revenue": _overview_metric(overview, "EVToRevenue"),
        "price_to_book": _overview_metric(overview, "PriceToBookRatio"),
        "eps_growth_yoy": _overview_metric(overview, "QuarterlyEarningsGrowthYOY"),
        "gross_margin": _overview_metric(overview, "GrossProfitTTM"),
        "operating_margin": _overview_metric(overview, "OperatingMarginTTM"),
        "net_margin": _overview_metric(overview, "ProfitMargin"),
        "roe": _overview_metric(overview, "ReturnOnEquityTTM"),
        "roic": None,
        "debt_to_equity": _overview_metric(overview, "DebtToEquity"),
        "current_ratio": _overview_metric(overview, "CurrentRatio"),
        "revenue_growth_yoy": _overview_metric(overview, "QuarterlyRevenueGrowthYOY"),
        "revenue_ttm": _overview_metric(overview, "RevenueTTM"),
        "ebitda_ttm": _overview_metric(overview, "EBITDA"),
        "net_income_ttm": _overview_metric(overview, "NetIncomeTTM"),
        "week_52_high": _overview_metric(overview, "52WeekHigh", "FiftyTwoWeekHigh"),
        "week_52_low": _overview_metric(overview, "52WeekLow", "FiftyTwoWeekLow"),
        "fcf_yield": None,
        "dividend_yield": _overview_metric(overview, "DividendYield"),
    }


def get_fundamentals(ticker: str) -> dict:
    """
    Key fundamental metrics. Alpha Vantage OVERVIEW first for P/E and revenue
    growth; yfinance only if Alpha Vantage fails or those fields are empty.
    """
    ticker = ticker.upper()
    av_key_set = bool(config.ALPHA_VANTAGE_API_KEY)

    cached = market_cache.get_fundamentals(ticker)
    if cached is not None:
        print(
            f"[fundamentals] {ticker}: using cache (source={cached.get('source', 'unknown')}); "
            f"ALPHA_VANTAGE_API_KEY set={av_key_set}"
        )
        return cached

    source = "Alpha Vantage" if av_key_set else "yfinance"
    print(
        f"[fundamentals] {ticker}: using {source}; "
        f"ALPHA_VANTAGE_API_KEY set={av_key_set}"
    )

    result: dict | None = None
    if config.ALPHA_VANTAGE_API_KEY:
        try:
            av = _fundamentals_alphavantage(ticker)
            if _core_metrics_present(av):
                result = av
            else:
                print(
                    f"[warn] Alpha Vantage returned empty P/E or revenue growth for {ticker}, "
                    "falling back to yfinance for missing fields"
                )
                yf = _fundamentals_yfinance(ticker)
                result = _merge_fundamentals(av, yf) if av.get("available") else yf
        except Exception as e:
            print(
                f"[error] Alpha Vantage fundamentals failed for {ticker}: {e}, "
                "falling back to yfinance"
            )

    if result is None:
        try:
            result = _fundamentals_yfinance(ticker)
        except Exception as e:
            note = f"Fundamentals collection failed for {ticker}: {e}"
            print(f"[error] {note}")
            return {"available": False, "note": note}

    market_cache.set_fundamentals(ticker, result)
    return result


def _core_metrics_present(data: dict) -> bool:
    return (
        data.get("available")
        and data.get("pe_ttm") is not None
        and data.get("revenue_growth_yoy") is not None
    )


def _merge_fundamentals(primary: dict, yf: dict) -> dict:
    """Prefer primary source values where present; fill gaps from yfinance."""
    if not yf.get("available"):
        return primary
    merged = dict(yf)
    for key, val in primary.items():
        if val is not None and key not in ("source", "note", "available"):
            merged[key] = val
    merged["available"] = True
    sources: list[str] = []
    if primary.get("available"):
        sources.append(primary.get("source", "Alpha Vantage"))
    if yf.get("available"):
        sources.append("yfinance")
    merged["source"] = "+".join(sources) if len(sources) > 1 else (sources[0] if sources else "unknown")
    return merged


def _fmp_get(endpoint: str, params: dict | None = None) -> list | dict:
    params = params or {}
    params["apikey"] = config.FMP_API_KEY
    r = requests.get(f"{FMP_BASE}/{endpoint}", params=params, timeout=20)
    r.raise_for_status()
    return r.json()


# ---------------------------------------------------------------------------
# Peers (FMP)
# ---------------------------------------------------------------------------

def _fundamentals_yfinance(ticker: str) -> dict:
    try:
        info = yf_ticker_info(ticker)
        if not info or not (info.get("longName") or info.get("shortName") or info.get("marketCap")):
            note = f"yfinance returned empty fundamentals for {ticker}"
            print(f"[error] {note}")
            return {"available": False, "note": note}

        return {
            "available": True,
            "source": "yfinance",
            "company_name": info.get("longName"),
            "sector": info.get("sector"),
            "industry": info.get("industry"),
            "market_cap": info.get("marketCap"),
            "pe_ttm": info.get("trailingPE"),
            "forward_pe": None,
            "peg_ratio": None,
            "ev_ebitda": info.get("enterpriseToEbitda"),
            "ev_revenue": info.get("enterpriseToRevenue"),
            "price_to_book": info.get("priceToBook"),
            "eps_growth_yoy": None,
            "gross_margin": info.get("grossMargins"),
            "operating_margin": info.get("operatingMargins"),
            "net_margin": info.get("profitMargins"),
            "roe": info.get("returnOnEquity"),
            "roic": None,
            "debt_to_equity": info.get("debtToEquity"),
            "current_ratio": info.get("currentRatio"),
            "revenue_growth_yoy": info.get("revenueGrowth"),
            "revenue_ttm": None,
            "ebitda_ttm": None,
            "net_income_ttm": None,
            "week_52_high": info.get("fiftyTwoWeekHigh"),
            "week_52_low": info.get("fiftyTwoWeekLow"),
            "fcf_yield": None,
            "dividend_yield": info.get("dividendYield"),
        }
    except Exception as e:
        note = f"yfinance fundamentals failed for {ticker}: {e}"
        print(f"[error] {note}")
        return {"available": False, "note": note}


# ---------------------------------------------------------------------------
# Peers
# ---------------------------------------------------------------------------

def get_peers(ticker: str) -> list[str]:
    """
    Peer list. FMP has a dedicated endpoint; without FMP the caller
    must supply peers manually (yfinance has no reliable peer data).
    """
    if config.FMP_API_KEY:
        try:
            data = _fmp_get(f"stock_peers", {"symbol": ticker})
            if data and isinstance(data, list):
                peers = data[0].get("peersList", [])
                return peers[: config.PEER_COUNT]
        except Exception as e:
            print(f"[error] FMP peers failed for {ticker}: {e}")
    return []


# ---------------------------------------------------------------------------
# Analyst data — Finnhub primary, FMP supplementary
# ---------------------------------------------------------------------------

def _finnhub_client():
    """Lazy Finnhub client; returns None if API key not set."""
    if not config.FINNHUB_API_KEY:
        return None
    try:
        import finnhub
        return finnhub.Client(api_key=config.FINNHUB_API_KEY)
    except Exception as e:
        print(f"[error] Finnhub client init failed: {e}")
        return None


def _overall_recommendation(strong_buy: int, buy: int, hold: int, sell: int, strong_sell: int) -> str:
    """Derive overall recommendation label from analyst counts."""
    bullish = strong_buy + buy
    bearish = strong_sell + sell
    if bullish > bearish and bullish > hold:
        return "Strong Buy" if strong_buy > buy else "Buy"
    if bearish > bullish and bearish > hold:
        return "Strong Sell" if strong_sell > sell else "Sell"
    return "Hold"


def get_analyst_consensus(ticker: str) -> dict:
    """Buy/hold/sell counts and overall recommendation from Finnhub."""
    if not config.FINNHUB_API_KEY:
        return {"available": False, "note": "Set FINNHUB_API_KEY for analyst consensus"}

    ticker = ticker.upper()
    cached = market_cache.get_analyst_consensus(ticker)
    if cached is not None:
        return cached

    result = _fetch_analyst_consensus(ticker)
    market_cache.set_analyst_consensus(ticker, result)
    return result


def _fetch_analyst_consensus(ticker: str) -> dict:
    try:
        client = _finnhub_client()
        if client is None:
            return {"available": False, "note": "Finnhub client unavailable"}

        trends = client.recommendation_trends(ticker.upper())
        if not trends:
            note = f"Finnhub returned no recommendation trends for {ticker}"
            print(f"[error] {note}")
            return {"available": False, "note": note}

        latest = trends[0]
        strong_buy = int(latest.get("strongBuy") or 0)
        buy = int(latest.get("buy") or 0)
        hold = int(latest.get("hold") or 0)
        sell = int(latest.get("sell") or 0)
        strong_sell = int(latest.get("strongSell") or 0)

        return {
            "available": True,
            "source": "Finnhub",
            "period": latest.get("period"),
            "strong_buy": strong_buy,
            "buy": buy,
            "hold": hold,
            "sell": sell,
            "strong_sell": strong_sell,
            "overall_recommendation": _overall_recommendation(
                strong_buy, buy, hold, sell, strong_sell
            ),
        }
    except Exception as e:
        note = f"Finnhub analyst consensus failed for {ticker}: {e}"
        print(f"[error] {note}")
        return {"available": False, "note": note}


def get_price_target(ticker: str) -> dict:
    """Mean, high, and low analyst price target from Finnhub."""
    if not config.FINNHUB_API_KEY:
        return {"available": False, "note": "Set FINNHUB_API_KEY for price targets"}

    try:
        client = _finnhub_client()
        if client is None:
            return {"available": False, "note": "Finnhub client unavailable"}

        pt = client.price_target(ticker.upper())
        if not pt or pt.get("targetMean") is None:
            note = f"Finnhub returned no price target for {ticker}"
            print(f"[error] {note}")
            return {"available": False, "note": note}

        return {
            "available": True,
            "source": "Finnhub",
            "mean": pt.get("targetMean"),
            "high": pt.get("targetHigh"),
            "low": pt.get("targetLow"),
            "median": pt.get("targetMedian"),
            "last_updated": pt.get("lastUpdated"),
        }
    except Exception as e:
        try:
            import finnhub
            if isinstance(e, finnhub.FinnhubAPIException) and getattr(e, "status_code", None) == 403:
                note = f"Finnhub price target 403 for {ticker}"
                print(f"[error] {note}")
                return {"available": False, "note": note, "finnhub_status": 403}
        except ImportError:
            pass
        note = f"Finnhub price target failed for {ticker}: {e}"
        print(f"[error] {note}")
        return {"available": False, "note": note}


def _price_target_yfinance(ticker: str) -> dict:
    """Fallback price targets from yfinance when Finnhub is unavailable."""
    try:
        pt = yf_analyst_price_targets(ticker)
        if not pt or pt.get("mean") is None:
            note = f"yfinance returned no price target for {ticker}"
            print(f"[error] {note}")
            return {"available": False, "note": note}

        return {
            "available": True,
            "source": "yfinance",
            "mean": pt.get("mean"),
            "high": pt.get("high"),
            "low": pt.get("low"),
            "median": pt.get("median"),
            "current": pt.get("current"),
        }
    except Exception as e:
        note = f"yfinance price target failed for {ticker}: {e}"
        print(f"[error] {note}")
        return {"available": False, "note": note}


def get_earnings_estimates(ticker: str) -> dict:
    """Next quarter EPS estimate from Finnhub."""
    if not config.FINNHUB_API_KEY:
        return {"available": False, "note": "Set FINNHUB_API_KEY for earnings estimates"}

    try:
        client = _finnhub_client()
        if client is None:
            return {"available": False, "note": "Finnhub client unavailable"}

        estimates = client.company_eps_estimates(ticker.upper(), freq="quarterly")
        rows = estimates.get("data") if isinstance(estimates, dict) else None
        if not rows:
            note = f"Finnhub returned no EPS estimates for {ticker}"
            print(f"[error] {note}")
            return {"available": False, "note": note}

        today = date.today().isoformat()
        future = [r for r in rows if str(r.get("period", "")) >= today]
        next_q = future[0] if future else rows[-1]

        return {
            "available": True,
            "source": "Finnhub",
            "period": next_q.get("period"),
            "quarter": next_q.get("quarter"),
            "year": next_q.get("year"),
            "eps_estimate": next_q.get("epsAvg"),
            "eps_high": next_q.get("epsHigh"),
            "eps_low": next_q.get("epsLow"),
            "num_analysts": next_q.get("numberAnalysts"),
        }
    except Exception as e:
        note = f"Finnhub earnings estimates failed for {ticker}: {e}"
        print(f"[error] {note}")
        return {"available": False, "note": note}


def get_analyst_data(ticker: str) -> dict:
    """
    Consensus analyst estimates and price targets.
    Finnhub primary (consensus, price target, EPS); FMP supplementary if configured.
    These ARE opinions — real analyst opinions, reported objectively.
    """
    out: dict = {"available": False}
    sources: list[str] = []

    if config.FINNHUB_API_KEY:
        consensus = get_analyst_consensus(ticker)
        price_target = get_price_target(ticker)
        if not price_target.get("available") and price_target.get("finnhub_status") == 403:
            print(f"[warn] Finnhub price target 403 for {ticker}, falling back to yfinance")
            price_target = _price_target_yfinance(ticker)
        earnings = get_earnings_estimates(ticker)
        out["consensus"] = consensus
        out["price_target"] = price_target
        out["earnings_estimates"] = earnings
        if any(x.get("available") for x in (consensus, price_target, earnings)):
            out["available"] = True
            sources.append("Finnhub")
        if price_target.get("available") and price_target.get("source") == "yfinance":
            if "yfinance" not in sources:
                sources.append("yfinance")

    if config.FMP_API_KEY:
        try:
            try:
                grades = _fmp_get(f"grade/{ticker}", {"limit": 10})
                out["recent_rating_actions"] = [
                    {
                        "date": g.get("date"),
                        "firm": g.get("gradingCompany"),
                        "action": g.get("newGrade"),
                        "previous": g.get("previousGrade"),
                    }
                    for g in grades[:10]
                ]
            except Exception as e:
                print(f"[error] FMP rating actions failed for {ticker}: {e}")
                out["recent_rating_actions"] = []

            try:
                pt = _fmp_get(f"price-target-consensus", {"symbol": ticker})
                out["fmp_price_target_consensus"] = pt[0] if pt else None
            except Exception as e:
                print(f"[error] FMP price target consensus failed for {ticker}: {e}")
                out["fmp_price_target_consensus"] = None

            if out.get("recent_rating_actions") or out.get("fmp_price_target_consensus"):
                out["available"] = True
                sources.append("FMP")
        except Exception as e:
            print(f"[error] FMP analyst data failed for {ticker}: {e}")

    if not out.get("available"):
        return {
            "available": False,
            "note": "Set FINNHUB_API_KEY or FMP_API_KEY for analyst consensus data",
        }

    out["source"] = ", ".join(sources)
    return out
